build:
  image: jojomi/hugo
  stage: build
  script:
  - apk add nodejs
  - npm install -g yarn
  - yarn
  - hugo
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  image: microsoft/azure-cli
  - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
  - az extension add -n webapp
  only:
    - master
  environment:
    name: production
    url: http://loconomics-pages.azurewebsites.net/pages
