# theme.toml template for a Hugo Loconomics theme

name = "Loconomics"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Loconomics Cooperative, Inc."
homepage = "https://www.loconomics.com/"
tags = []
features = []
min_version = "0.01"

[author]
  name = "Tony Kwok"
  homepage = "https://www.loconomics.com/"