publish_mode: editorial_workflow
media_folder: static/pages/media
public_folder: /pages/media

backend:
  name: github
  repo: loconomics/loconomics-pages

collections:

  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
